### ISSUE TITLE
Naming conventions overlap with FT

### ISSUE THREAD

**Issue by aarmour** [PearsonEducation/he-origami#6]
The module [naming conventions](http://pearsoneducation.github.io/he-origami/docs/component-spec/modules/#naming-conventions) mandate the `o-` prefix. Does it matter if our component names overlap with FT's? If so, we should consider adding a qualifier to change the prefix, e.g. `o-he-`.

**Comment by kaelig** [comment]
Unless you're using FT Origami components there's probably no problem using the `o-` prefix for your own components.

If you think this is going to be an issue then I'd recommend something shorter than `o-he-` because class names might end up being longer than necessary.

**Comment by aarmour** [comment]
I agree—I'd prefer to keep it as short/simple as possible. I doubt we'll be using the FT components.
